// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsphhlzlnhqmtvkdrnjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzcGhobHpsbmhxbXR2a2Rybmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTE3NzcsImV4cCI6MjA2OTk4Nzc3N30.Bc_am4y5NQN3ZttELF7P6wlUysTuq4vqW_mVNH2SK4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});